# Generated by Django 2.2.5 on 2019-12-15 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('likedislike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
