# Generated by Django 2.2.12 on 2020-07-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likedislike', '0002_likedislike_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='vote',
        ),
    ]
