# Generated by Django 2.2.12 on 2020-07-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='album',
        ),
        migrations.DeleteModel(
            name='BookmarkAlbum',
        ),
    ]
