# Generated by Django 2.2.12 on 2020-07-27 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20200727_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='recipes.Embed'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
