# Generated by Django 2.2.13 on 2020-08-03 11:33

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdpr_assist
import stream_django.activity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymised', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('body', models.TextField(verbose_name='Treść')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('author', models.ForeignKey(on_delete=gdpr_assist.ANONYMISE(django.db.models.deletion.SET_NULL), to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, stream_django.activity.Activity),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymised', models.BooleanField(default=False)),
                ('body', models.TextField(verbose_name='Treść')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=gdpr_assist.ANONYMISE(django.db.models.deletion.SET_NULL), to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Question')),
            ],
            bases=(models.Model, stream_django.activity.Activity),
        ),
    ]
