# Generated by Django 2.2.13 on 2020-08-07 08:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Treść'),
        ),
    ]
