# Generated by Django 2.2.13 on 2020-07-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200730_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tagulous_Question_tags',
        ),
    ]
