# Generated by Django 2.2 on 2019-11-25 10:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
