# Generated by Django 2.2 on 2019-11-25 13:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Treść'),
        ),
    ]
