# Generated by Django 2.2 on 2019-11-25 18:50

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20191125_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', max_count=5, to='questions.Tagulous_Question_tags', verbose_name='Tagi'),
        ),
    ]
