# Generated by Django 2.2 on 2019-11-25 22:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20191125_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Treść'),
        ),
    ]
