# Generated by Django 2.2 on 2019-04-15 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='Awatar profilu')),
                ('bio', models.TextField(verbose_name='O mnie')),
                ('url', models.URLField(max_length=255, verbose_name='Link do bloga lub innej strony')),
                ('facebook', models.URLField(max_length=255, verbose_name='Profil lub fanpage na Facebooku')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
