# Generated by Django 2.2.13 on 2020-07-30 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdpr_assist


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='anonymised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='anonymised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=gdpr_assist.ANONYMISE(django.db.models.deletion.SET_NULL), related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=gdpr_assist.ANONYMISE(django.db.models.deletion.SET_NULL), to=settings.AUTH_USER_MODEL),
        ),
    ]
