# Generated by Django 2.2 on 2019-11-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
