# Generated by Django 2.2.5 on 2019-12-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191126_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='defaultavatar.png', upload_to='avatar', verbose_name='Awatar profilu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='O mnie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profil lub fanpage na Facebooku'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link do bloga lub innej strony'),
        ),
    ]
