# Generated by Django 2.2.13 on 2020-08-11 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdpr_assist
import stream_django.activity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=gdpr_assist.ANONYMISE(django.db.models.deletion.SET_NULL), to=settings.AUTH_USER_MODEL, verbose_name='uzytkownicy')),
            ],
            bases=(models.Model, stream_django.activity.Activity),
        ),
    ]
