# Generated by Django 2.2.7 on 2019-11-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='blog', verbose_name='Miniatura'),
            preserve_default=False,
        ),
    ]
