# Generated by Django 2.2.13 on 2020-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(blank=True, default='defaultbgcategory.jpg', help_text='Dodając zdjęcie jesteś w stanie wyróżnić kategorię, jeśli jednak tego nie zrobisz nic się nie stanie. :)', null=True, upload_to='tlo', verbose_name='Tło kategorii'),
        ),
    ]
