# Generated by Django 2.2.13 on 2020-08-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
