# Generated by Django 2.2 on 2019-04-15 17:01

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190415_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeCategory'),
            preserve_default=False,
        ),
    ]
