# Generated by Django 2.2 on 2019-04-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190416_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embed',
            name='category',
        ),
    ]
