# Generated by Django 2.1.5 on 2019-04-16 15:56

from django.db import migrations
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_embed_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='recipes.RecipeCategory', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='embed',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Opis'),
        ),
    ]
