# Generated by Django 2.1.5 on 2019-04-17 20:48

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20190416_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embed',
            name='category',
        ),
        migrations.AddField(
            model_name='embed',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='embeds', to='recipes.RecipeCategory', verbose_name='Kategoria'),
        ),
    ]
