# Generated by Django 2.2.7 on 2019-11-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipecategory_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes'),
            preserve_default=False,
        ),
    ]
