# Generated by Django 2.2.7 on 2019-11-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_embed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes'),
        ),
    ]
