# Generated by Django 2.2.5 on 2019-12-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20191209_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='body',
            field=models.TextField(blank=True, help_text='To pole nie jest obowiązkowe. Jeśli chcesz, możesz napisać co konkretnie ma być dodawane do tej kategorii.', verbose_name='Opis kategorii'),
        ),
    ]
