# Generated by Django 2.2.12 on 2020-06-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20200630_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipecategory',
            old_name='full_name',
            new_name='parentname',
        ),
    ]
